app/admin/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, jsonify, request, abort
from app.models import *
from app.decorators import *
from forms import *
from datetime import datetime
import json
mod = Blueprint('admin', __name__, url_prefix='/admin', template_folder='templates')


@mod.route('/', methods=['GET', 'POST'])
@only_admin
def admin():
    return render_template('admin.html', admins=Admin.all(), admin_form=AdminForm())


@mod.route('/add_admin', methods=['GET', 'POST'])
@only_admin
def add_admin():
    admin_form = AdminForm(request.form)
    key = ''
    if admin_form.validate():
        admin = Admin(email=admin_form.email.data)
        admin.put()
        key = admin.key()
    return json.dumps({'valid': admin_form.validate_on_submit(), 'key': str(key), 'email': admin_form.email.data})


@mod.route('/add_edit_about_me', methods=['GET', 'POST'])
@only_admin
def add_edit_about_me():
    return render_template('add_edit_about_me.html', photos=PhotoAboutMe().all(), article_about_me="")


@mod.route('/edit_education', methods=['GET', 'POST'])
@only_admin
def edit_education():
    article = Education().all().get()
    if not article:
        article = ""
    else:
        article = article.body
    return render_template('edit_article.html', article=article, link="submit_education")


@mod.route('/submit_education', methods=['GET', 'POST'])
@only_admin
def submit_education():
    article = Education.all().get()
    data = json.loads(request.data)
    if not article:
        article = Education(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/edit_work', methods=['GET', 'POST'])
@only_admin
def edit_work():
    article = Work().all().get()
    if not article:
        article = ""
    else:
        article = article.body
    return render_template('edit_article.html', article=article, link="submit_work")


@mod.route('/submit_work', methods=['GET', 'POST'])
@only_admin
def submit_work():
    article = Work.all().get()
    data = json.loads(request.data)
    if not article:
        article = Work(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/edit_project', methods=['GET', 'POST'])
@only_admin
def edit_project():
    article = Project().all().get()
    if not article:
        article = ""
    else:
        article = article.body
    return render_template('edit_article.html', article=article, link="submit_project")


@mod.route('/submit_project', methods=['GET', 'POST'])
@only_admin
def submit_project():
    article = Project.all().get()
    data = json.loads(request.data)
    if not article:
        article = Project(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/edit_my_project', methods=['GET', 'POST'])
@only_admin
def edit_my_project():
    article = MyProject().all().get()
    if not article:
        article = ""
    else:
        article = article.body
    return render_template('edit_article.html', article=article, link="submit_my_project")


@mod.route('/submit_my_project', methods=['GET', 'POST'])
@only_admin
def submit_my_project():
    article = MyProject.all().get()
    data = json.loads(request.data)
    if not article:
        article = MyProject(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/edit_traineeship', methods=['GET', 'POST'])
@only_admin
def edit_traineeship():
    article = Traineeship().all().get()
    if not article:
        article = ""
    else:
        article = article.body
    return render_template('edit_article.html', article=article, link="submit_traineeship")


@mod.route('/submit_traineeship', methods=['GET', 'POST'])
@only_admin
def submit_traineeship():
    article = Traineeship.all().get()
    data = json.loads(request.data)
    if not article:
        article = Traineeship(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/edit_courses', methods=['GET', 'POST'])
@only_admin
def edit_courses():
    article = Courses().all().get()
    if not article:
        article = ""
    else:
        article = article.body
    return render_template('edit_article.html', article=article, link="submit_courses")


@mod.route('/submit_courses', methods=['GET', 'POST'])
@only_admin
def submit_courses():
    article = Courses.all().get()
    data = json.loads(request.data)
    if not article:
        article = Courses(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/submit_conference', methods=['GET', 'POST'])
@only_admin
def submit_conference():
    article = Conference.all().get()
    data = json.loads(request.data)
    if not article:
        article = Conference(body=data["article"])
        article.put()
    else:
        article.body = data["article"]
        article.put()
    return json.dumps({'valid': True})


@mod.route('/edit_contact', methods=['GET', 'POST'])
@only_admin
def edit_contacts():
    return render_template('edit_contact.html', emails=ContactsEmail.all(), email_form=EmailForm(),
                           contacts=ContactSocialForm(), networks=ContatctsSocial.all(),
                           contact_form=AllContactForm(),
                           allcontacts=AllContacts.all())


@mod.route('/add_photo', methods=['GET', 'POST'])
@only_admin
def add_photo():
    photo = PhotoAboutMe()
    if request.files['photo']:
        photo.photo = db.Blob(request.files['photo'].read())
        photo.put()
        id = photo.key().id()
        return json.dumps({'valid': True, 'id': id, 'key': str(photo.key())})
    return json.dumps({'valid': False})


@mod.route('/add_email', methods=['GET', 'POST'])
@only_admin
def add_email():
    email_form = EmailForm(request.form)
    key = ''
    if email_form.validate():
        Email = ContactsEmail(email=email_form.email.data)
        Email.put()
        key = Email.key()
    return json.dumps({'valid': email_form.validate_on_submit(), 'key': str(key), 'email': email_form.email.data})


@mod.route('/add_network', methods=['GET', 'POST'])
@only_admin
def add_network():
    networkform = ContactSocialForm(request.form)
    key = ''
    nameerror = False
    urlerror = False
    logo = False
    if networkform.validate():
        Network = ContatctsSocial(name=networkform.name.data, url=networkform.url.data)
        if request.files['logo']:
            Network.logo = db.Blob(request.files['logo'].read())
            logo = True
        Network.put()
        key = Network.key()
    else:
        if networkform.name.errors:
            nameerror = True
        if networkform.url.errors:
            urlerror = True
    return json.dumps({'valid': networkform.validate_on_submit(),
                       'key': str(key),
                       'url': networkform.url.data,
                       'name': networkform.name.data,
                       'name-error': nameerror,
                       'url-error': urlerror,
                       'logo': logo})


@mod.route('/add_column', methods=['GET', 'POST'])
@only_admin
def add_column():
    columnform = AllContactForm(request.form)
    key = ''
    columnerror = False
    valueerror = False
    if columnform.validate():
        Column = AllContacts(nameColumn=columnform.column.data, valueColumn=columnform.value.data)
        Column.put()
        key = Column.key()
    else:
        if columnform.column.errors:
            columnerror = True
        if columnform.value.errors:
            valueerror = True
    return json.dumps({'valid': columnform.validate_on_submit(),
                       'key': str(key),
                       'column': columnform.column.data,
                       'value': columnform.value.data,
                       'column-error': columnerror,
                       'value-error': valueerror})


@mod.route('/submit_articles_about_me', methods=['GET', 'POST'])
@only_admin
def submit_articles_about_me():
    article = ArticleAboutMe.all().get()
    if not article:
        article = ArticleAboutMe(body=request.args.get('article'))
        article.put()
    else:
        article.body = request.args.get('article')
        article.put()
    return json.dumps({'valid': True})


@mod.route('/delete_photo/<string:key>', methods=['GET', 'POST'])
@only_admin
def delete_photo(key):
    db.delete(key)
    return json.dumps({})


@mod.route('/delete_by_key/<string:key>', methods=['GET', 'POST'])
@only_admin
def delete_by_key(key):
    db.delete(key)
    return json.dumps({})


# Blog
@mod.route('/blog/group/<int:group_id>', methods=['POST'])
@only_admin
def blog_group_get(group_id):
    return jsonify(group=GroupsOfBlogs.get(group_id))


@mod.route('/blog/group/all', methods=['POST'])
@only_admin
def blog_group_get_all():
    return jsonify(groups=GroupsOfBlogs.get().all())


@mod.route('/blog/group/add', methods=['POST'])
@only_admin
def blog_group_add():
    data = json.loads(request.data)

    try:
        group = GroupsOfBlogs(name=data["name"], color=data["color"])
    except (ValueError, KeyError, TypeError):
        return abort(400)

    group.put()

    return json.dumps({"key": group.key().id()})


@mod.route('/blog/group/<int:group_id>/edit', methods=['POST'])
@only_admin
def blog_group_edit(group_id):
    data = json.loads(request.data)
    group = GroupsOfBlogs.get_by_id(group_id)

    try:
        group.name = data["name"]
        group.color = data["color"]
    except (ValueError, KeyError, TypeError):
        return abort(400)

app/admin/templates/add_blog_articles.html
{% extends "admin.html" %}
{% block content %}
<div class="col-md-7">
<form>
            <textarea name="editor1">
                This is my textarea to be replaced with CKEditor.
            </textarea>
</form>
</div>
<div class="col-md-3">
</div>
</div>
{% endblock  %}
{% block scripts %}
    <script src="../../static/ckeditor/ckeditor.js"></script>
    <script src="../../static/ckeditor/adapters/jquery.js"></script>
<script>
                    $("#editor1")
                                            .ckeditor();

            </script>
{% endblock %}

app/admin/templates/add_edit_about_me.html
{% extends "admin.html" %}
{% block buttons %}
<center><input id="ajaxsubmit" type="button" class="btn btn-primary" value="  Подтвердить изменения  "/></center>

{% endblock %}
{% block content %}
<div class="col-md-7">
<form  id="about">
            <textarea id="article_about_me" name="article_about_me">{{ article_about_me }}</textarea>
</form>
</div>
<div class="col-md-3">
{% for photo in photos %}
					<div class="thumbnail text-center" id= "{{ photo.key().id() }}">
						<div class="overlay-container">
							<img src="/refresh_about_me_img/{{ photo.key().id() }}" style="width:100%;">
							<div class="overlay-content">
								<a href="/refresh_about_me_img/{{ photo.key().id() }}">http://127.0.0.1:8080/refresh_about_me_img/{{ photo.key().id() }}</a>
								<br><div class="btn btn-danger" onclick="DeletePhoto('{{ photo.key()}}','{{ photo.key().id() }}')">Delete</div>
							</div>
						</div>
					</div>
{% endfor %}
					<form id="photo"><center><div class="thumbnail text-center"><input type="file" name="photo"/><div class="btn btn-default" onclick="AddPhoto()">Submit</div></div></center></form>
</div>
{% endblock  %}
{% block scripts %}
    <script src="../../static/ckeditor/ckeditor.js"></script>
    <script src="../../static/ckeditor/adapters/jquery.js"></script>
<script>

                    $("#article_about_me")
                                            .ckeditor();

$("#ajaxsubmit").click(function()
{
    var postData = {'article': $("#article_about_me").val()};
    $.ajax({
        url : "/admin/submit_articles_about_me",
        type: "GET",
        data : postData,
        dataType: "JSON",
        success: function(result)
        {
            if(result['valid'])
            {
                var message= "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a>Успешно Измененно</div>";
                setTimeout(function(){$('#ajaxsubmit').before(message)},3000);
            }
        }
    })
});
function DeletePhoto(key, id)
{
    var url = "/admin/delete_photo/"+key;
    $.ajax(
    {
        url : url,
        type : "POST",
        data :{},
        contentType: false,
        processData: false,
        datatype: "JSON",
        success: function()
        {
            var k = document.getElementById(id);
            k.remove();
        }
    }
    )
}

function AddPhoto()
{
    var data = new FormData($('#photo')[0]);
    $.ajax(
    {
        url : "/admin/add_photo",
        type : "POST",
        data : data,
        contentType: false,
        processData: false,
        dataType: "json",
        success :function(result)
        {
            if(result['valid']){
                var src = "'http://127.0.0.1:8080/refresh_about_me_img/" + result['id'] +"'";
                var new_photo="<div class='thumbnail text-center' id=" +result['id'] +"><div class='overlay-container'><img src="+src+
                " style='width:100%;'>" + "<div class='overlay-content'><a href="+src+">"+src+
                "</a><br><div class='btn btn-danger' onclick=DeletePhoto('"+result['key']+"','"+result['id']+"') >Delete</div></div></div></div>";
                setTimeout(function(){$('#photo').before(new_photo)},3000)
                }
        }

    }
    )

}
</script>
{% endblock %}

app/admin/templates/admin.html
<!DOCTYPE html>
<html>
<head lang="en">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="../static/css/bootstrap-theme.min.css">

    {#     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">#}
    {# <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> #}
    <script src="../static/js/jquery.min.js"></script>
    <link rel="stylesheet" href="../../static/css/AdminStyle.css">
    <meta charset="UTF-8">
    <title>Admin panel</title>
    {# <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> #}
    <script src="../static/js/jquery-1.11.2.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
<div clas="container">
    <div class="col-md-2 adminmenu">
        <div class="sidebar-nav">
            <div class="well menu">
                <ul class="nav nav-list">
                    <li class="nav-header active"><a href="{{ url_for('admin.admin') }}" class="text-center">Admin Menu</a></li>
                    <li><a href="{{ url_for('admin.edit_work') }}" class="text-center">Редактировать работу</a></li>
                    <li><a href="{{ url_for('admin.edit_education') }}" class="text-center">Редактировать образование</a></li>
                    <li><a href="{{ url_for('admin.edit_project') }}" class="text-center">Редактировать участие в проэктах</a></li>
                    <li><a href="{{ url_for('admin.edit_my_project') }}" class="text-center">Редактировать мои проэкты</a></li>
                    <li><a href="{{ url_for('admin.edit_traineeship') }}" class="text-center">Редактировать стажировку</a></li>
                    <li><a href="{{ url_for('admin.edit_courses') }}" class="text-center">Редактировать курсы</a></li>
                    <li><a href="{{ url_for('admin.edit_contacts') }}" class="text-center">Редактировать контакты</a></li>
                    <li><a href="{{ url_for('admin.blog') }}" class="text-center">Управление блогом</a></li>
                    <li><a href="{{ url_for('admin.font') }}" class="text-center">Управление шрифтами</a></li>
                    <!--<li><a href="/admin/add_edit_about_me" class="text-center">Edit Article About Me</a></li>-->
                </ul>
                {% block buttons %}
                {% endblock %}
                <img class="logo" width="100%" src="../../static/img/flask.png">
            </div>

        </div>

    </div>
    {% block content %}
        <div class="col-md-2">
            <form class="add-email">
                <div class="thumbnail text-center">
                    <div class="overlay-container">
                        <div class="form-group">
                            {{ admin_form.hidden_tag() }}
                            {{ admin_form.email(class="form-control", placeholder='Email only Google') }}
                            <br><div class="btn btn-success" onclick="AddEmail()">Add Admin</div>
                        </div>
                    </div>
                </div>
            </form>
            {% for admin in admins %}
                <div class="thumbnail text-center" id="{{ admin.key() }}">
                    <div class="overlay-container">
                        <p>Admin Email: {{ admin.email }}</p>
                        <div class="overlay-content">
                            <br><div class="btn btn-danger" onclick="DeleteByKey('{{ admin.key() }}')">Delete EMail</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock %}
</div>
{% block scripts %}
    <script>
        function AddEmail()
        {
            var data = new FormData($('.add-email')[0]);
            $.ajax({
                type: "POST",
                url: "add_admin",
                data: data,
                contentType: false,
                processData: false,
                dataType: "json",
                success: function (result){
                    if(result['valid'])
                    {
                        var deleteemail = 'DeleteByKey("'+result['key']+'")';
                        $('.add-email > .form-group').removeClass('has-error');
                        $('#email').val('');
                        var blockemail = "<div class='thumbnail text-center' id='" +result['key'] + "'>" +
                                "<div class=s'overlay-container'><p>Email: "+ result['email']+"</p><div class='overlay-content'><br>" +
                                "<div class='btn btn-danger' onclick='" +deleteemail+ "'>Delete Email" +
                                "</div></div></div></div>";
                        $(".add-email").after(blockemail);
                    }
                    else
                    {
                        $('#email').parent().addClass('has-error');
                    }
                }
            })

        }
        function DeleteByKey(key)
        {
            var url = "/admin/delete_by_key/"+key;
            $.ajax(
                    {
                        url : url,
                        type : "POST",
                        data :{},
                        contentType: false,
                        processData: false,
                        datatype: "JSON",
                        success: function()
                        {
                            document.getElementById(key).remove();
                        }
                    }
            )
        }
    </script>
{% endblock %}
</body>
</html>

app/admin/templates/admin_blog.html
{% extends "admin.html" %}

{% block head %}
    <link href="../static/blog/css/bootstrap-colorpicker.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/blog/css/admin_blog.css">
{% endblock %}

{% block content %}
    <div class="col-md-10">
        <div class="wrap">
            <div class="panel panel-own-full panel-transparent">
                <div class="panel-header">
                    <h1></h1>
                </div>
                <div class="panel-body">
                    <div class="blog-menu">
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-header">
                                <h2>Категории</h2>
                            </div>
                        </div>
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-header">
                                <h2>Добавить категорию</h2>
                            </div>
                            <div class="panel-body">
                                <form id="form-group-add" class="form-group" action="{{ url_for('admin.blog_group_add') }}" method="post" fastform>
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" placeholder="Название категорий" required>
                                    </div>
                                    <div class="form-group">
                                        <input name="color" type="text" class="form-control input-colorpicker" placeholder="Цвет катогрии" required>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-default pull-right">Добавить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-body">
                                <form id="form-group-edit" class="form-group" method="post" fastform action-delete="{{ url_for('admin.blog_group_delete', group_id=0) }}" action-edit="{{ url_for('admin.blog_group_edit', group_id=0) }}">
                                    <div class="form-group">
                                        <select class="form-control" not-input select-group>
                                            {% for group in groups %}
                                                <option value="{{ group.key().id() }}" color="{{ group.color }}">{{ group.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" placeholder="Название категорий" required>
                                    </div>
                                    <div class="form-group">
                                        <input name="color" type="text" class="form-control input-colorpicker" placeholder="Цвет категории" required />
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" action-name="delete" class="btn btn-default pull-left">Удалить</button>
                                        <button type="submit" action-name="edit" class="btn btn-default pull-right">Изменить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="panel panel-blog-menu panel-blue">
                            <div class="panel-header">
                                <h2>Посты</h2>
                            </div>
                        </div>
                        <div class="panel panel-blog-content panel-blue container-fluid">
                            <div class="panel-header">
                                <h2>Добавить пост</h2>
                            </div>
                            <div class="panel-body">
                                <form class="form-group" fastform action="{{ url_for('admin.blog_add') }}" method="post" id="form-blog-add">
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" placeholder="Название поста" required>
                                    </div>
                                    <div class="form-group">
                                        <select name="group" class="form-control" select-group required>
                                            {% for group in groups %}
                                                <option value="{{ group.key().id() }}" color="{{ group.color }}">{{ group.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <textarea name="content" required></textarea>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-default pull-right">Добавить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        {% for blog in blogs %}
                            <div class="panel panel-blog-content panel-blue container-fluid" style="background-color: {{ blog.group.color }}">
                                <div class="panel-body">
                                    <form class="form-group" fastform action-edit="{{ url_for('admin.blog_edit', blog_id=blog.key().id()) }}" action-delete="{{ url_for('admin.blog_delete', blog_id=blog.key().id()) }}" method="post" id="form-blog-edit">
                                        <div class="form-group">
                                            <input name="name" type="text" class="form-control" placeholder="Название поста" required value="{{ blog.name }}">
                                        </div>
                                        <div class="form-group">
                                            <select name="group" class="form-control" select-group required>
                                                {% for group in groups %}
                                                    <option value="{{ group.key().id() }}" color="{{ group.color }}" {% if blog.group == group %}selected{% endif %}>{{ group.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <textarea name="content" required>{{ blog.content|safe }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" action-name="delete" class="btn btn-default pull-left">Удалить</button>
                                            <button type="submit" action-name="edit" class="btn btn-default pull-right">Изменить</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        {% endfor %}
                        {#<div class="row text-center">
                            <button type="button" class="btn btn-default" aria-label="Left Align">Загрузить еще</button>
                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="../static/blog/js/bootstrap-colorpicker.js"></script>
    <script src="../static/blog/ckeditor/ckeditor.js"></script>
    <script src="../static/blog/ckeditor/adapters/jquery.js"></script>
    <script src="../static/blog/js/fastforms.js"></script>
    <script src="../static/blog/js/script.js"></script>
{% endblock %}

app/admin/templates/edit_article.html
{% extends "admin.html" %}
{% block head %}
<link rel="stylesheet" href="../../static/CodeMirror/lib/codemirror.css">

{% endblock %}
{% block buttons %}
<center><input id="ajaxsubmit" type="button" class="btn btn-primary" value="  Подтвердить изменения  "/></center>

{% endblock %}
{% block content %}
<div class="col-md-10">
<div>
            <textarea id="edit">{{ article }}</textarea>
</div>
</div>
{% endblock  %}
{% block scripts %}
<script src="../../static/CodeMirror/lib/codemirror.js"></script>
<script src="../../static/CodeMirror/addon/selection/selection-pointer.js"></script>
<script src="../../static/CodeMirror/mode/xml/xml.js"></script>
<script src="../../static/CodeMirror/mode/javascript/javascript.js"></script>
<script src="../../static/CodeMirror/mode/css/css.js"></script>
<script src="../../static/CodeMirror/mode/htmlmixed/htmlmixed.js"></script>
    <script src="../../static/ckeditor/ckeditor.js"></script>
    <script src="../../static/ckeditor/adapters/jquery.js"></script>
<script>


      // Define an extended mixed-mode that understands vbscript and
      // leaves mustache/handlebars embedded templates in html mode
      var mixedMode = {
        name: "htmlmixed",
        scriptTypes: [{matches: /\/x-handlebars-template|\/x-mustache/i,
                       mode: null},
                      {matches: /(text|application)\/(x-)?vb(a|script)/i,
                       mode: "vbscript"}]
      };






                    $("#edit")
                                            .ckeditor();


$("#ajaxsubmit").click(function() {
    //alert(JSON.stringify(editor.getValue()));
    var postData = { 'article':$("#edit").val()};
    $.ajax({
        url : "/admin/{{ link }}",
        type: "POST",
        data : JSON.stringify(postData),//JSON.stringify(editor.getValue()),
        dataType: "JSON",
        contentType: "application/json",
        success: function(result)
        {
            if(result['valid'])
            {
                var message= "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a>Успешно Измененно</div>";
                setTimeout(function(){$('#ajaxsubmit').before(message)},1000);
            }
        }
    })
});
</script>
{% endblock %}